create schema if not exists private;
create extension if not exists pg_cron with schema pg_catalog;

create type public.app_role as enum ('manager','coach','member');
create type public.account_status as enum ('pending','active','blocked','rejected');
create type public.gender_type as enum ('female','male');
create type public.subscription_status as enum ('awaiting_payment','active','expired','cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null, full_name text not null, whatsapp_e164 text,
  gender public.gender_type not null,
  role public.app_role not null default 'member',
  status public.account_status not null default 'pending',
  language text not null default 'ar' check (language in ('ar','en')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.membership_plans (
  id bigint generated by default as identity primary key,
  code text not null unique check (code in ('daily','monthly','quarterly')),
  name_ar text not null, name_en text not null,
  price_ils integer not null check (price_ils > 0),
  duration_days integer not null check (duration_days > 0), active boolean not null default true
);

create table public.subscriptions (
  id uuid primary key default gen_random_uuid(), member_id uuid not null references public.profiles(id) on delete cascade,
  plan_id bigint not null references public.membership_plans(id), starts_on date, ends_on date,
  status public.subscription_status not null default 'awaiting_payment', renewal_approved boolean not null default false,
  created_at timestamptz not null default now(),
  constraint subscription_dates_valid check (ends_on is null or starts_on is null or ends_on >= starts_on)
);

create table public.cash_payments (
  id uuid primary key default gen_random_uuid(), subscription_id uuid not null references public.subscriptions(id),
  amount_ils integer not null check (amount_ils > 0), received_by uuid not null references public.profiles(id),
  paid_at timestamptz not null default now(), note text
);

create table public.measurements (
  id uuid primary key default gen_random_uuid(), member_id uuid not null references public.profiles(id) on delete cascade,
  recorded_by uuid not null references public.profiles(id), height_cm numeric(5,2) not null check (height_cm between 50 and 260),
  weight_kg numeric(5,2) not null check (weight_kg between 20 and 400), waist_cm numeric(5,2), chest_cm numeric(5,2),
  hips_cm numeric(5,2), arm_cm numeric(5,2), thigh_cm numeric(5,2), recorded_at timestamptz not null default now()
);

create table public.health_profiles (
  member_id uuid primary key references public.profiles(id) on delete cascade,
  birth_date date, activity_level text, goal text, medical_notes text, updated_at timestamptz not null default now()
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(), recipient_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('subscription_expires_today','subscription_expiring','payment_confirmed','account_approved','coach_message')),
  title_ar text not null, title_en text not null, body_ar text not null, body_en text not null,
  related_entity_type text, related_entity_id uuid, read_at timestamptz, created_at timestamptz not null default now()
);

create table public.audit_log (
  id bigint generated by default as identity primary key, actor_id uuid references public.profiles(id),
  action text not null, entity_type text not null, entity_id text, details_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.member_programs (
  id uuid primary key default gen_random_uuid(), member_id uuid not null references public.profiles(id) on delete cascade,
  created_by uuid not null references public.profiles(id), goal text not null check (goal in ('weight_loss','muscle_gain','fitness')),
  training_days integer not null check (training_days between 2 and 6), daily_calories integer not null check (daily_calories between 1000 and 5000),
  protein_g integer not null check (protein_g between 40 and 400), carbs_g integer not null check (carbs_g between 50 and 700),
  fats_g integer not null check (fats_g between 20 and 250), water_liters numeric(3,1) not null check (water_liters between 1 and 8),
  workout_plan jsonb not null default '[]'::jsonb, meal_plan jsonb not null default '[]'::jsonb,
  notes text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create unique index idx_profiles_email_lower on public.profiles(lower(email));
create index idx_profiles_status_role on public.profiles(status,role);
create index idx_subscriptions_member_status on public.subscriptions(member_id,status);
create index idx_subscriptions_ends_on_active on public.subscriptions(ends_on) where status='active';
create index idx_measurements_member_date on public.measurements(member_id,recorded_at desc);
create index idx_notifications_recipient_unread on public.notifications(recipient_id,created_at desc) where read_at is null;
create unique index idx_notifications_expiry_once on public.notifications(recipient_id,type,related_entity_id) where type='subscription_expires_today';
create unique index idx_member_programs_one_active on public.member_programs(member_id) where active;
create index idx_member_programs_member_created on public.member_programs(member_id,created_at desc);

insert into public.membership_plans(code,name_ar,name_en,price_ils,duration_days) values
('daily','دخول يومي','Day pass',15,1),('monthly','اشتراك شهري','Monthly',130,30),('quarterly','اشتراك 3 أشهر','3 months',330,90);

create or replace function private.is_staff() returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=(select auth.uid()) and role in ('manager','coach') and status='active') $$;
revoke all on function private.is_staff() from public;
grant execute on function private.is_staff() to authenticated;

create or replace function private.is_manager() returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=(select auth.uid()) and role='manager' and status='active') $$;
revoke all on function private.is_manager() from public;
grant execute on function private.is_manager() to authenticated;

create or replace function private.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
declare selected_plan bigint; selected_gender public.gender_type;
begin
  selected_gender:=case when new.raw_user_meta_data->>'gender'='male' then 'male'::public.gender_type else 'female'::public.gender_type end;
  insert into public.profiles(id,email,full_name,whatsapp_e164,gender)
  values(new.id,new.email,coalesce(nullif(new.raw_user_meta_data->>'full_name',''),'عضو جديد'),nullif(new.raw_user_meta_data->>'whatsapp_e164',''),selected_gender);
  select id into selected_plan from public.membership_plans where code=coalesce(new.raw_user_meta_data->>'requested_plan','monthly') and active limit 1;
  if selected_plan is not null then insert into public.subscriptions(member_id,plan_id) values(new.id,selected_plan); end if;
  return new;
end $$;
revoke all on function private.handle_new_user() from public;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();

create or replace function private.notify_account_status() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if old.status='pending' and new.status='active' then
    insert into public.notifications(recipient_id,type,title_ar,title_en,body_ar,body_en,related_entity_type,related_entity_id)
    values(new.id,'account_approved','تم قبول حسابك','Account approved','تم قبول الحساب. أكمل الدفع الكاش لتفعيل الاشتراك.','Your account was approved. Complete the cash payment to activate membership.','profile',new.id);
  end if;
  return new;
end $$;
revoke all on function private.notify_account_status() from public;
create trigger on_profile_status_changed after update of status on public.profiles for each row execute function private.notify_account_status();

create or replace function private.activate_cash_subscription(p_subscription uuid,p_amount integer,p_note text default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_duration integer; v_price integer; v_member uuid;
begin
  if not private.is_staff() then raise exception 'not_authorized'; end if;
  select s.member_id,mp.duration_days,mp.price_ils into v_member,v_duration,v_price
  from public.subscriptions s join public.membership_plans mp on mp.id=s.plan_id where s.id=p_subscription for update;
  if v_member is null then raise exception 'subscription_not_found'; end if;
  if p_amount<>v_price then raise exception 'invalid_amount'; end if;
  insert into public.cash_payments(subscription_id,amount_ils,received_by,note) values(p_subscription,p_amount,auth.uid(),p_note);
  update public.subscriptions set starts_on=current_date,ends_on=current_date+(v_duration-1),status='active' where id=p_subscription;
  insert into public.notifications(recipient_id,type,title_ar,title_en,body_ar,body_en,related_entity_type,related_entity_id)
  values(v_member,'payment_confirmed','تم تفعيل اشتراكك','Membership activated','تم تأكيد الدفعة وبدأ اشتراكك اليوم.','Your cash payment was confirmed and your membership starts today.','subscription',p_subscription);
end $$;
revoke all on function private.activate_cash_subscription(uuid,integer,text) from public;
grant execute on function private.activate_cash_subscription(uuid,integer,text) to authenticated;

create or replace function public.activate_cash_subscription(p_subscription uuid,p_amount integer,p_note text default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_duration integer; v_price integer; v_member uuid; v_role public.app_role;
begin
  select role into v_role from public.profiles where id=(select auth.uid());
  if v_role is null or v_role not in ('manager','coach') then raise exception 'not_authorized'; end if;
  select s.member_id,mp.duration_days,mp.price_ils into v_member,v_duration,v_price
  from public.subscriptions s join public.membership_plans mp on mp.id=s.plan_id
  where s.id=p_subscription and s.status='awaiting_payment' for update;
  if v_member is null then raise exception 'subscription_not_found_or_already_paid'; end if;
  if p_amount<>v_price then raise exception 'invalid_amount'; end if;
  insert into public.cash_payments(subscription_id,amount_ils,received_by,note)
  values(p_subscription,p_amount,(select auth.uid()),p_note);
  update public.subscriptions set starts_on=current_date,ends_on=current_date+(v_duration-1),status='active'
  where id=p_subscription;
  insert into public.notifications(recipient_id,type,title_ar,title_en,body_ar,body_en,related_entity_type,related_entity_id)
  values(v_member,'payment_confirmed','تم تفعيل اشتراكك','Membership activated','تم تأكيد الدفعة وبدأ اشتراكك اليوم.','Your cash payment was confirmed and your membership starts today.','subscription',p_subscription);
end $$;
revoke all on function public.activate_cash_subscription(uuid,integer,text) from public;
revoke all on function public.activate_cash_subscription(uuid,integer,text) from anon;
grant execute on function public.activate_cash_subscription(uuid,integer,text) to authenticated;

create or replace function public.update_own_profile(p_full_name text,p_whatsapp text default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  if (select auth.uid()) is null then raise exception 'not_authorized'; end if;
  if length(trim(p_full_name))<2 then raise exception 'invalid_name'; end if;
  update public.profiles set full_name=trim(p_full_name),whatsapp_e164=nullif(trim(p_whatsapp),''),updated_at=now()
  where id=(select auth.uid());
  insert into public.audit_log(actor_id,action,entity_type,entity_id,details_json)
  values((select auth.uid()),'profile_updated','profile',(select auth.uid())::text,jsonb_build_object('fields',array['full_name','whatsapp_e164']));
end $$;
revoke all on function public.update_own_profile(text,text) from public,anon;
grant execute on function public.update_own_profile(text,text) to authenticated;

create or replace function private.create_expiry_notifications() returns integer language plpgsql security definer set search_path=public as $$
declare inserted_count integer;
begin
  update public.subscriptions set status='expired' where status='active' and ends_on<current_date;
  with expiring as (
    select s.id,s.member_id,p.full_name from public.subscriptions s join public.profiles p on p.id=s.member_id where s.status='active' and s.ends_on=current_date
  ), member_notices as (
    insert into public.notifications(recipient_id,type,title_ar,title_en,body_ar,body_en,related_entity_type,related_entity_id)
    select member_id,'subscription_expires_today','اشتراكك ينتهي اليوم','Your membership expires today','يمكنك طلب التجديد من حسابك بعد موافقتك.','You can request renewal after your approval.','subscription',id from expiring on conflict do nothing returning 1
  ), manager_notices as (
    insert into public.notifications(recipient_id,type,title_ar,title_en,body_ar,body_en,related_entity_type,related_entity_id)
    select mgr.id,'subscription_expires_today','اشتراك ينتهي اليوم','Membership expires today','ينتهي اشتراك '||e.full_name||' اليوم.','The membership for '||e.full_name||' expires today.','subscription',e.id
    from expiring e cross join public.profiles mgr where mgr.role='manager' and mgr.status='active' on conflict do nothing returning 1
  ) select (select count(*) from member_notices)+(select count(*) from manager_notices) into inserted_count;
  return inserted_count;
end $$;
revoke all on function private.create_expiry_notifications() from public;
select cron.schedule('strong-gym-expiry-notifications','0 * * * *',$$select private.create_expiry_notifications();$$);

alter table public.profiles enable row level security; alter table public.membership_plans enable row level security;
alter table public.subscriptions enable row level security; alter table public.cash_payments enable row level security;
alter table public.measurements enable row level security; alter table public.health_profiles enable row level security;
alter table public.notifications enable row level security; alter table public.audit_log enable row level security;
alter table public.member_programs enable row level security;

create policy "plans readable" on public.membership_plans for select to anon,authenticated using(active);
create policy "profiles readable" on public.profiles for select to authenticated using(id=(select auth.uid()) or private.is_staff());
create policy "manager profiles update" on public.profiles for update to authenticated using(private.is_manager()) with check(private.is_manager());
create policy "subscriptions readable" on public.subscriptions for select to authenticated using(member_id=(select auth.uid()) or private.is_staff());
create policy "staff subscriptions update" on public.subscriptions for update to authenticated using(private.is_staff()) with check(private.is_staff());
create policy "payments readable" on public.cash_payments for select to authenticated using(private.is_staff() or exists(select 1 from public.subscriptions s where s.id=subscription_id and s.member_id=(select auth.uid())));
create policy "measurements readable" on public.measurements for select to authenticated using(member_id=(select auth.uid()) or private.is_staff());
create policy "staff measurements insert" on public.measurements for insert to authenticated with check(private.is_staff());
create policy "staff measurements update" on public.measurements for update to authenticated using(private.is_staff()) with check(private.is_staff());
create policy "health readable" on public.health_profiles for select to authenticated using(member_id=(select auth.uid()) or private.is_staff());
create policy "health self insert" on public.health_profiles for insert to authenticated with check(member_id=(select auth.uid()));
create policy "health self update" on public.health_profiles for update to authenticated using(member_id=(select auth.uid())) with check(member_id=(select auth.uid()));
create policy "notifications readable" on public.notifications for select to authenticated using(recipient_id=(select auth.uid()));
create policy "notifications mark read" on public.notifications for update to authenticated using(recipient_id=(select auth.uid())) with check(recipient_id=(select auth.uid()));
create policy "audit staff read" on public.audit_log for select to authenticated using(private.is_staff());
create policy "programs readable" on public.member_programs for select to authenticated using(member_id=(select auth.uid()) or private.is_staff());
create policy "staff programs insert" on public.member_programs for insert to authenticated with check(private.is_staff() and created_by=(select auth.uid()));
create policy "staff programs update" on public.member_programs for update to authenticated using(private.is_staff()) with check(private.is_staff());

grant usage on schema public to anon,authenticated; grant select on public.membership_plans to anon,authenticated;
grant select,update on public.profiles to authenticated; grant select,update on public.subscriptions to authenticated;
grant select on public.cash_payments to authenticated; grant select,insert,update on public.measurements to authenticated;
grant select,insert,update on public.health_profiles to authenticated; grant select,update on public.notifications to authenticated;
grant select on public.audit_log to authenticated;
grant select,insert,update on public.member_programs to authenticated;

analyze;

-- Workout tracking and adaptive progression
create table if not exists public.workout_logs (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references public.profiles(id) on delete cascade,
  program_id uuid not null references public.member_programs(id) on delete cascade,
  session_date date not null default current_date,
  day_index integer not null check (day_index between 0 and 6),
  exercise_name text not null check (char_length(exercise_name) between 2 and 160),
  exercise_type text not null check (exercise_type in ('strength','cardio','mobility')),
  target_text text,
  weight_kg numeric(6,2) check (weight_kg is null or weight_kg between 0 and 500),
  reps integer check (reps is null or reps between 0 and 1000),
  duration_minutes integer check (duration_minutes is null or duration_minutes between 0 and 600),
  difficulty text check (difficulty is null or difficulty in ('easy','good','hard')),
  completed boolean not null default false,
  notes text check (notes is null or char_length(notes) <= 500),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(member_id,program_id,session_date,day_index,exercise_name)
);
create index if not exists idx_workout_logs_member_date on public.workout_logs(member_id,session_date desc);
create index if not exists idx_workout_logs_program_day on public.workout_logs(program_id,day_index,exercise_name,session_date desc);
alter table public.workout_logs enable row level security;
create policy "workout logs readable" on public.workout_logs for select to authenticated using(member_id=(select auth.uid()) or private.is_staff());
create policy "members insert workout logs" on public.workout_logs for insert to authenticated with check(member_id=(select auth.uid()));
create policy "members update workout logs" on public.workout_logs for update to authenticated using(member_id=(select auth.uid())) with check(member_id=(select auth.uid()));
grant select,insert,update on public.workout_logs to authenticated;

-- Daily meals, macros, and water tracking
create table if not exists public.meal_logs (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references public.profiles(id) on delete cascade,
  logged_on date not null default current_date,
  meal_name text not null check (char_length(meal_name) between 2 and 120),
  calories integer not null check (calories between 0 and 5000),
  protein_g numeric(6,1) not null default 0 check (protein_g between 0 and 500),
  water_ml integer not null default 0 check (water_ml between 0 and 10000),
  created_at timestamptz not null default now()
);
create index if not exists idx_meal_logs_member_date on public.meal_logs(member_id,logged_on desc);
alter table public.meal_logs enable row level security;
create policy "meal logs readable" on public.meal_logs for select to authenticated using(member_id=(select auth.uid()));
create policy "members insert meal logs" on public.meal_logs for insert to authenticated with check(member_id=(select auth.uid()));
create policy "members delete meal logs" on public.meal_logs for delete to authenticated using(member_id=(select auth.uid()));
grant select,insert,delete on public.meal_logs to authenticated;
